GET http://localhost:5000/api/users/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjEzMWYwMDQ2ZjUxZGQyYTQzYzhlNTciLCJpYXQiOjE3MTI5Njg2MjMsImV4cCI6MTcxMzA1NTAyM30.bjlbY_fTNJVKBHc75RfMInGqU6Tt6qm7aFYidrbhltA